local config = require("modules/config")
local Cron   = require("modules/Cron")

radioManager = {}

function radioManager:new(radioMod)
	local o = {}

    o.rm = radioMod
    o.radios = {}
    o.initialized = false

    o.isMounted = false

	self.__index = self
   	return setmetatable(o, self)
end

function radioManager:loadRadios() -- Loads radios based on radios.json file, generated by .asi
    self.initialized = false

    if not config.fileExists("radios/radiosInfo.json") then
        return false
    end

    local radios = config.loadFile("radios/radiosInfo.json")

    for _, path in pairs(radios.paths) do
        if not config.fileExists("radios/" .. path .. "/metadata.json") then
            print("[RadioMod] Could not find metadata.json file in \"radios/" .. path .. "\"")
        elseif not config.fileExists("radios/" .. path .. "/songInfos.json") then
            print("[RadioMod] Could not find songInfos.json file in \"radios/" .. path .. "\", try restarting your game")
        else
            local metadata = config.loadFile("radios/" .. path .. "/metadata.json")
            local songs = config.loadFile("radios/" .. path .. "/songInfos.json")

            local r = require("modules/radio"):new(self.rm)
            r:load(metadata, songs, path)
            self.radios[#self.radios + 1] = r
        end
    end

    self.initialized = true

    return true
end

function radioManager:getRadioByName(name)
    for _, radio in pairs(self.radios) do
        if name == radio.name then
            return radio
        end
    end

    return nil
end

function radioManager:switchToRadio(radio)
    if radio.active then return end
    self:disableCustomRadio()
    Cron.After(0.1, function()
        GetMountedVehicle(GetPlayer()):GetBlackboard():SetBool(GetAllBlackboardDefs().Vehicle.VehRadioState, true)
        GetMountedVehicle(GetPlayer()):GetBlackboard():SetName(GetAllBlackboardDefs().Vehicle.VehRadioStationName, radio.name)
        radio:activate()
    end)
end

function radioManager:disableCustomRadio()
    for _, radio in pairs(self.radios) do
        radio:deactivate()
    end
end

function radioManager:update()
    local veh = GetMountedVehicle(GetPlayer())
    if veh then
        self.isMounted = true
        if veh:IsEngineTurnedOn() then
            local name = veh:GetBlackboard():GetName(GetAllBlackboardDefs().Vehicle.VehRadioStationName)
            local radio = self:getRadioByName(name.value)

            if radio and not radio.active then
                radio:activate()
            end
        end
    elseif self.isMounted then
        self.isMounted = false
        self:disableCustomRadio()
    end
end

function radioManager:handleMenu()
    local veh = GetMountedVehicle(GetPlayer())
    if not veh then return end

    local name = veh:GetBlackboard():GetName(GetAllBlackboardDefs().Vehicle.VehRadioStationName)
    local radio = self:getRadioByName(name.value)

    if radio then
        if radio.active then
            radio:deactivate()
        end
    end
end

function radioManager:handleTS() -- trainSystem comp
    if self.rm.runtimeData.ts then
        local train = self.rm.runtimeData.ts.stationSys.activeTrain
        if train and train.playerMounted then
            for _, radio in pairs(self.radios) do
                if radio.active then
                    GetMountedVehicle(GetPlayer()):ToggleRadioReceiver(false)
                end
            end
        end
    end
end

return radioManager